#include "wrapper.h"


extern "C" tree_api *create_tree(const tree_options_t &opt) {
    return new lbtree_wrapper(opt);
}

lbtree_wrapper::lbtree_wrapper(const tree_options_t &opt) {
    worker_id= 0; // the main thread will use worker[0]'s mem/nvm pool

    // assume mempool size is same as nvmpool size, although they can be different
    the_thread_mempools.init(opt.num_threads, opt.pool_size, 4096);
    the_thread_nvmpools.init(opt.num_threads, opt.pool_path.c_str(), opt.pool_size);

    // allocate a 4KB page for the tree in worker 0's pool
    char *nvm_addr= (char *)nvmpool_alloc(4096);
    tree_ = new lbtree(nvm_addr, false);
}

lbtree_wrapper::~lbtree_wrapper() {
    delete tree_;
}

bool lbtree_wrapper::find(const char *key, size_t key_sz, char *value_out) {
    int pos;
    // key generated by pibench is already an integer, so we can convert it to long long
    long long key_ll = atoll(key);
    void *p = tree_->lookup(key_ll, &pos);

    // void *recptr = tree_->get_recptr(p, pos);
    // TODO: Populate value_out
    return pos >= 0; // valid position within the leaf node
}

bool lbtree_wrapper::insert(const char *key, size_t key_sz, const char *value, size_t value_sz) {
    // TODO: See if we can modify lbtree to use const char *
    // Currently we have to copy value before inserting it because it is const
    // and lbtree does not require const
    // char *dest = (char *)malloc(value_sz+1);
    // key generated by pibench is already an integer, so we can convert it to long long
    // tree_->insert(atoll(key), strcpy(dest, value));
    while (*key < '0' || *key > '9') key++;
    long long key_ll = atoll(key);
    std::cout << "inserting " << key << " converted to " << key_ll << std::endl;
    tree_->insert(key_ll, value);
    // TODO: Can check if the value is inserted, but that might require extra 'lookup' call
    return true;
}

bool lbtree_wrapper::update(const char *key, size_t key_sz, const char *value, size_t value_sz) {
    // There is not explciit update method in lbtree
    // Redirect to insert
    return insert(key, key_sz, value, value_sz);
}

int lbtree_wrapper::scan(const char *key, size_t key_sz, int scan_sz, char *&values_out) {
    // Operation not implemented in lbtree
    return -1;
}

bool lbtree_wrapper::remove(const char *key, size_t key_sz) {
    // key generated by pibench is already an integer, so we can convert it to long long
    tree_->del(atoll(key));
    // TODO: Can check if the value is deleted, but that might require extra 'lookup' call
    return true;
}